version: '3'
services:
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    volumes: 
        - /root/wanghuan/docker/mysql/data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/my.cnf
        - ./mysql/init:/docker-entrypoint-initdb.d/
  redis:
    build: ./redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
        - /root/wanghuan/docker/redis/data:/data 
    environment: 
        - TZ=Asia/Shanghai
  nginx: 
    build: ./nginx 
    ports: 
      - 3000:3000 
      - 3100:3100 
      - 8000:8000 
    volumes: 
        - /home/huanhuan/myweb/myvue:/home/huanhuan/myweb/myvue 
        - /home/huanhuan/myweb/images:/home/huanhuan/myweb/images 
        - /home/huanhuan/myweb/myvueadmin:/home/huanhuan/myweb/myvueadmin
  ftp-service:
    build: ./ftp-service/build
    depends_on:
      - redis
      - mysql
      - nginx
    ports: 
        - 8071:8071
    volumes: 
        - /home/huanhuan/myweb/images:/home/huanhuan/myweb/images
    network_mode: host